
version: '3.8'
services: 
  database:
      image: mysql
      volumes:
          - cls-dbdata:/var/lib/mysql
      networks:
          - cls-net          
      environment:
          MYSQL_DATABASE: ${DB_DATABASE}
          MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
          MYSQL_PASSWORD: ${DB_PASSWORD}
      ports:
          - 33061:3306
networks:
    cls-net:
        driver: bridge
volumes:
    cls-dbdata:
        driver: local